ci/cd:
  head: "ci/*"
  
refactor:
  head: "refactor/*"

enhancement:
  head: "feature/*"

bug:
  head: ["bugfix/*", "fix/*"]

documentation:
  head: "docs/*"

housekeeping:
  head: "housekeeping/*"

release:
  base: "release/*"