version: '3.9'

services:
  crm_app:
    container_name: crm_app
    image: srelucas/crm-backend:latest
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "3000:3000"
    depends_on:
      - crm_db
  crm_db:
    container_name: crm_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  crm_pgadmin:
    container_name: crm_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucas.duerksen.work@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "5050:80"

volumes:  
  pgdata: {}