server:
  http:
    port: 3000
    hostname: "localhost"
db:
  postgres:
    dbHost: "0.0.0.0"
    dbUser: "postgres"
    dbPassword: "postgres"
    dbName: "postgres"
    dbPort: "5432"
    dbSslMode: "disable"