apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm-backend
  name: pgadmin  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080  # Exposes container port
          envFrom:
            - configMapRef:
                name: pgadmin-config
