# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # name: "BUILD"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.3']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Display Go version
      run: go version
    
    - name: Install dependencies
      run: |
        go get .
        go get github.com/gorilla/mux
      
    - name: Verify dependencies
      run: go mod verify
      
    - name: Build
      run: go build -v ./...
  
  # linter:
  #   name: "LINTING"
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       go-version: ['1.21.3']
    steps:
    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...
  
  # tests:
  #   name: "TESTING"
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Test
      run: go test -race -vet=off ./...
  
  # documentation:
  #   name: "DOCUMENTATION"
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Install Go
        run: go get -u github.com/swaggo/swag/cmd/swag
      - name: Run swagger
        run: swag fmt
      - name: swag init
        run: swag init